### ISSUE TITLE
where is the training script?

### ISSUE THREAD

**Issue by lucasjinreal** [vita-epfl/detection-attributes-fields#2]
where is the training script?

**Comment by lucasjinreal** [comment]
training seems error with command:

```
python3 -m openpifpaf.train \
  --output ./output/model.pth \
  --dataset jaad \
  --jaad-root-dir ./data/JAAD \
  --jaad-subset default \
  --jaad-training-set train \
  --jaad-validation-set val \
  --log-interval 10 \
  --val-interval 1 \
  --epochs 5 \
  --batch-size 4 \
  --lr 0.0005 \
  --lr-warm-up-start-epoch -1 \
  --weight-decay 5e-4 \
  --momentum 0.95 \
  --basenet fn-resnet50 \
  --pifpaf-pretraining \
  --detection-bias-prior 0.01 \
  --jaad-head-upsample 2 \
  --jaad-pedestrian-attributes all \
  --fork-normalization-operation power \
  --fork-normalization-duplicates 35 \
  --lambdas 7.0 7.0 7.0 7.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 \
  --attribute-regression-loss l1 \
  --attribute-focal-gamma 2 \
  --auto-tune-mtl

```

error

```
TypeError: Caught TypeError in replica 4 on device 4.
Original Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'image_batch'

```

**Comment by lucasjinreal** [comment]
am using 0.12.10

**Comment by lucasjinreal** [comment]
Same error on 0.12.9

**Comment by taylormordan** [comment]
Does the error still happen when using a single GPU, without nn.parallel?
If not, try to increase the batch size to at least the number of GPUs you use.

In case you try to use multiple GPUs, please also consider the instructions from OpenPifPaf for [HPC environements](https://openpifpaf.github.io/train.html#cloud-and-hpc) and for [using DistributedDataParallel](https://openpifpaf.github.io/train.html#distributeddataparallel).

**Comment by lucasjinreal** [comment]
@taylormordan thank u, I managed run with single GPU. But may I ask, how to visualize all attributes predict? I currently only can get box and a pedestrian class. How to get all attributes?

**Comment by taylormordan** [comment]
I am not sure whether it is really possible to visualize all attributes in a clear way on top of images. For now, only boxes are displayed.
By using option `--write-predictions` in eval, you can get a .json file with the predictions for all attributes.

**Comment by lucasjinreal** [comment]
@taylormordan thank u. May I ask how to determine a binary class can be treated as right prediction. For example, I have a prediction like this:

```
{'confidence': 0.7049740271887865,
     'center': [539.7777431063013, 203.0687464490376],
     'height': 48.67216188822299,
     'width': 20.32498713871383,
     'will_cross': 0.23939526556875051,
     'time_to_crossing': 3.1874745443157892,
     'is_crossing': 0.11537566100994213,
     'look': 0.5146412251820849,
     'walk': 0.5529353177575399,
     'motion_direction': [0.7770541468002509, 0.2229458531997491],
     'pose_back': 0.40875780078509016,
     'pose_front': 0.5219438320060517,
     'pose_left': 0.2818236707353809,
     'pose_right': 0.310370836488774,
     'group_size': [0.38827195961500005, 0.3714142140694758, 0.1369592924057246, 0.10335453390979962],
     'reaction': [0.7793715983462424, 0.08976904078422139, 0.02935772410143072, 0.10150163676810559],
     'gender': [
         0.5588417181480548, 0.4411582818519452],
     'backpack': 0.21750788098826287,
     'bag_elbow': 0.2962495332825278,
     'bag_hand': 0.4215295251377109,
     'bag_left_side': 0.40374783156959665,
     'bag_right_side': 0.3928066857376692,
     'bag_shoulder': 0.30825509288424474,
     'cap': 0.21127464318860859,
     'clothes_below_knee': 0.26738910520459463,
     'clothes_lower_dark': 0.7531116975030885,
     'clothes_upper_dark': 0.5957375548502214,
     'clothes_lower_light': 0.23880681658411174,
     'clothes_upper_light': 0.40351325402249466,
     'hood': 0.32138367775146975,
     'object': 0.19303421156685957,
     'phone': 0.2522995927800927,
     'stroller_cart': 0.2641057331708776,
     'sunglasses': 0.1769353182403742,
     'age': [0.19776218333340928, 0.5787150957961689, 0.22352272087042185]}
```

So, let see how much score above can we treat this object is `phone` enabled?

**Comment by taylormordan** [comment]
I am not sure I understand your question.
If you ask how to differentiate positive and negative predictions, I simply threshold the scores at 0.5 for binary attributes, and take the class with the max score for multi-class attributes.
